[formatter.prettier]
command = "prettier"
options = ["--ignore-path", ".prettierignore", "--write"]
includes = [
  "*.css",
  "*.scss",
  "*.html",
  "*.js",
  "*.jsx",
  "*.ts",
  "*.tsx",
  "*.cjs",
  "*.mjs",
  "*.json",
  "*.md",
  "*.mdx",
  "*.yml",
  "*.yaml",
]

[formatter.toml]
command = "taplo"
options = ["format", "$@"]
includes = ["*.toml"]
