name: Lint

on:
  push:
    branches:
      - main
      - feat/*
      - feature/*
      - hotfix/*
      - release/*
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: ${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: ${{ runner.os }}-nix-store-

      - name: Install treefmt
        run: nix profile install 'nixpkgs#treefmt'

      - name: Install taplo
        run: nix profile install 'nixpkgs#taplo'

      - name: Install prettier
        run: nix profile install 'nixpkgs#nodePackages.prettier'

      - name: Run treefmt
        id: treefmt
        run: |
          treefmt \
            --allow-missing-formatter \
            --fail-on-change \
            --no-cache \
            --formatters prettier \
            --formatters toml

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Format files"
          title: "[bot] Format files with treefmt"
          body: "This is an auto-generated PR to format files."
          labels: bot
          delete-branch: true
